### ISSUE TITLE
Error since newest release: DisabledBackend Attribute error

### ISSUE THREAD

**Issue by laurensvdwiel** [cmbi/metadome#58]
When Querying a new gene that has not yet been prebuild, the following error occurs:

```
2019-08-14 09:04:10,079 INFO sqlalchemy.engine.base.Engine {'lower_1': 'pms2'}
2019-08-14 09:04:10,100 INFO sqlalchemy.engine.base.Engine ROLLBACK
2019-08-14 09:04:12,888 - ERROR - Unhandled exception:'DisabledBackend' object has no attribute '_get_task_meta_for'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/metadome/presentation/api/routes.py", line 106, in get_visualization_status_for_transcript
    status = get_visualization_status(transcript_id)
  File "/usr/src/app/metadome/controllers/job.py", line 106, in get_visualization_status
    return result.status
  File "/usr/local/lib/python3.5/site-packages/celery/result.py", line 471, in state
    return self._get_task_meta()['status']
  File "/usr/local/lib/python3.5/site-packages/celery/result.py", line 410, in _get_task_meta
    return self._maybe_set_cache(self.backend.get_task_meta(self.id))
  File "/usr/local/lib/python3.5/site-packages/celery/backends/base.py", line 359, in get_task_meta
    meta = self._get_task_meta_for(task_id)
AttributeError: 'DisabledBackend' object has no attribute '_get_task_meta_for'
```
@cbaakman, can you look into this?

**Comment by cbaakman** [comment]
it mentions it's using a 'DisabledBackend', which is not as it supposed to be. Accoring to https://github.com/cmbi/metadome/blob/master/metadome/default_settings.py#L16, the backend should be redis.

Did you do anything special when running?

**Comment by laurensvdwiel** [comment]
The server was redeployed after this commit:
https://github.com/cmbi/metadome/commit/b779405c36c54efd97d01e6cf44e518917cce01c

The redeploy contained changes as of this commit: https://github.com/cmbi/metadome/commit/d8c9479762a1c1ef54cca484db94ec6f0a368a1d

Before this the issue was not there.

Can you see if any of these changes may have caused this error?

**Comment by cbaakman** [comment]
I'm unable to reproduce the error using this test:
https://github.com/cmbi/metadome/blob/fix-visualization/tests/integration/test_tasks.py#L46

Could you check if redis is running on your deployment server?

**Comment by laurensvdwiel** [comment]
Fixed as of https://github.com/cmbi/metadome/commit/b99377b8e74a5363b2ac2cdab4d9ad8f37f3b79a
